export const queryKeys = {
  profile: ['profile'],
  company: ['company'],
  branches: ['branches'],
  users: ['users'],
  roles: ['roles'],
  leads: ['leads'],
  deals: ['deals'],
  dealActivities: (id) => ['deal-activities', id],
  clients: ['clients'],
  quotations: ['quotations'],
  invoices: ['invoices'],
  commissions: ['commissions'],
  projects: ['projects'],
  tasks: ['tasks'],
  approvals: ['approvals'],
  documents: ['documents'],
  sops: ['sops'],
  attendance: ['attendance'],
  kpis: ['kpis'],
  reviews: ['reviews'],
  goals: ['goals'],
  rewards: ['rewards'],
  training: ['training'],
  leaveRequests: ['leave-requests'],
  payroll: ['payroll'],
  announcements: ['announcements'],
  expenses: ['expenses'],
  budgets: ['budgets'],
  messages: ['messages'],
  notifications: ['notifications'],
  socialAccounts: ['social-accounts'],
  socialMetrics: ['social-metrics'],
  departments: ['departments'],
  employees: ['employees'],
}
